#!/bin/bash

# If any errors occur during operation, this script stop running.
set -e

# Global constants
DOT_DIRECTORY="${HOME}/Dotfiles"
DOT_TARBALL="https://github.com/Natch/Dotfiles/tarball/master"
REMOTE_URL="git@github.com:Natch/Dotfiles.git"

# Check the command exits and can be able to use it.
has() {
  type "$1" > /dev/null 2>&1
}

# Echo help
help() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]
Commands:
  deploy: Replace existing dotfiles to symbolic links
   -f Force remove the dotfile if it's already there
  initialize: Install/Update HomeBrew, then set up develop environment (e.g. anyenv)
Arguments:
  -h Print help (this message)
EOF
  exit 1
}

# Argument options
while getopts :h opt; do
  case ${opt} in
    h)
      help
      ;;
  esac
done
shift $((OPTIND - 1))

# Working only OS X(darwin*), otherwise exit 1.
case ${OSTYPE} in
  darwin*)
    ;;
  *)
    echo $(tput setaf 1)Working only OS X!!$(tput sgr0)
    exit 1
    ;;
esac

# If DOT_DIRECTORY is missing, clone and extract the dotfiles from repository.
if [ ! -d ${DOT_DIRECTORY} ]; then
  echo "Downloading dotfiles..."
  mkdir ${DOT_DIRECTORY}

  if has "git"; then
    git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
  else
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOT_TARBALL}
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOT_DIRECTORY}
    rm -f ${HOME}/dotfiles.tar.gz
  fi

  echo $(tput setaf 2)Download dotfiles complete!. ✔︎$(tput sgr0)
fi

cd ${DOT_DIRECTORY}

# Deployment (Replace existing dotfiles to symbolic links)
deploy() {
  for f in .??*
  do
    # If "-f" option is added,
    # Force remove the dotfile although it's already there.
    [ -n "${OVERWRITE}" -a -e ${HOME}/${f} ] && rm -f ${HOME}/${f}
    if [ ! -e ${HOME}/${f} ]; then
      # If you have ignore files, add file/directory name here
      [[ ${f} = ".git" ]] && continue
      [[ ${f} = ".gitignore" ]] && continue
      ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
    else
      echo "$(tput setaf 1)${f} has already been in HOME Directory.$(tput sgr0)"
    fi
  done

  echo $(tput setaf 2)Deploy dotfiles complete!. ✔︎$(tput sgr0)
}

# Install / Update HomeBrew, then install fomulaes and casks.
run_brew() {
  # Install brew
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if has "brew"; then
    # Update brew
    echo "Updating Homebrew..."
    brew update
    brew upgrade
    [[ $? ]] && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    # brew tap
    brew tap 'caskroom/cask' # Homebrew Cask

    # Install usual packages using brew command.
    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
      'anyenv'
      'aws-elasticbeanstalk'
      'awscli'
      'circleci'
      'git'
      'graphviz'
      'hstr'
      'jq'
      'mysql@5.7'
      'redis'
      'tfenv'
      'tflint'
      'the_silver_searcher'
      'tree'
      'wget'
      'yarn'
      'zsh'
    )

    local installed=`brew list`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew install $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    # Install each application if needed by brew cask
    local -a missing_formulae=()
    local -a desired_formulae=(
      'alfred'
      'bettertouchtool'
      'cakebrew'
      'chromedriver'
      'dash'
      'docker'
      'dozer'
      'fork'
      'iterm2'
      'keyboardcleantool'
      'ngrok'
      'postman'
      'sequel-pro'
      'skitch'
      'spectacle'
      'tableplus'
      'visual-studio-code'
    )

    local installed=`brew cask list`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew cask install $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    # Cleanup accumulate old versions of a fomula.
    echo "Cleanup Homebrew..."
    brew cleanup

    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
  fi
}

# anyenv
run_anyenv() {
  if [ ! -d ${HOME}/.anyenv ]; then
    echo "Downloading anyenv..."

    git clone https://github.com/riywo/anyenv ~/.anyenv

    echo "$(tput setaf 2)Download anyenv ✔︎$(tput sgr0)"

    if has "anyenv"; then
      echo "Installing anyenv..."
      anyenv install rbenv
      anyenv install pyenv
      anyenv install phpenv
      anyenv install ndenv
      exec $SHELL -l

      echo "$(tput setaf 2)Installed anyenv ✔︎$(tput sgr0)"

    else
      echo "$(tput setaf 1)anyenv not existed path.$(tput sgr0)"
      exit 1
    fi
  fi

  # pyenv
  if has "pyenv"; then
    # Install python 3.X.X (latest)
    latest3x=`pyenv install --list | grep -v - | grep -oe '3.\d.\d*$' | tail -n 1`
    current=`pyenv versions | grep -oe '\d\.\d\{1,\}\.\d\{1,\}\([ ]\|$\)' | tail -n 1 | tr -d "[:space:]"`
    if [[ ${current} != ${latest3x} ]]; then
      echo "Installing pyenv install ${latest3x}"
      pyenv install ${latest3x}
      pyenv global ${latest3x}
    else
      echo "Already pyenv global version is ${latest3x}"
      pyenv global ${latest3x}
    fi

    if has 'pip'; then
      pip install --upgrade pip
      pip install powerline-status
      echo "$(tput setaf 2)powerline-status install completed. ✔︎$(tput sgr0)"
    else
      echo "$(tput setaf 1)pip not installed.$(tput sgr0)"
      exit 1
    fi
  else
    echo "$(tput setaf 1)pyenv not installed.$(tput sgr0)"
    exit 1
  fi
}

# Installation and initialize
initialize() {
  run_brew

  # Install zplug (zsh plugin)
  [ ! -d ${HOME}/.zplug ] && curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh

  # Change shell to zsh
  # [ ${SHELL} != "/bin/zsh"  ] && chsh -s /bin/zsh

  # Install dein.vim (vim plugin manager)
  if [ ! -d ${HOME}/.vim/repos/github.com/Shougo/dein.vim ]; then
    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
    sh ./installer.sh ~/.vim
    rm -rf ./installer.sh
    echo "$(tput setaf 2)dein.vim install complete. ✔︎$(tput sgr0)"
  else
    echo "$(tput setaf 2)dein.vim already installed. ✔︎$(tput sgr0)"
  fi

  run_anyenv

  echo "$(tput setaf 2)Initialize complete!. ✔︎$(tput sgr0)"
}

command=$1
option=$2

[ $# -gt 0 ] && shift

case $command in
  deploy)
    if [ -n "${option}" -a "${option}" = "-f" ]; then
      OVERWRITE=true
    fi
    deploy
    ;;
  init*)
    initialize
    ;;
  *)
    help
    ;;
esac

exit 0
